### ISSUE TITLE
public and private front end

### ISSUE THREAD

**Issue by stefanplug** [RIPE-NCC/rpki-validator#28]
Can we have 2 separate instances for the rpki-validator-app front end?

I would like to make the front end public so that everyone can verify that our trust anchors are up to date, but I do not want to expose update buttons or check boxes to the public, although I would like to have them available on a private instance when I connect via a different port which is never going to be available to the public internet.

exposing a password box is fine internally, but no-one on the public side has any business changing or updating anything so i don't even want to offer that option there.

**Comment by timbru** [comment]
The validator supports "kiosk" mode. If you use this it will require a password for any update, so Joe public cannot make changes. The buttons are still visible though.

We are not planning changes to the front end of this version of the validator in the short term because we plan to replace it altogether over the next few months.

Our first aim there is to make a more stable version of this software that can easily be installed and kept up to date on servers: RPMs for redhat/centos is our first target, but dependent on feedback this can be extended to other distributions.

The initial version will only have an API and CLI, because we have heard quite often from network operators that they prefer to run this without a front-end interface altogether. We plan to work on a UI later though and when we do we can definitely take your account in mind.
