### ISSUE TITLE
[info] number of dns request is important 

### ISSUE THREAD

**Issue by MrCamp146** [RIPE-NCC/rpki-validator#35]
Hello,
I am currently doing lab tests to implement RPKI on the backbone of my company and have seen a high number of DNS queries.
I installed rpki-validator-2.24 and rpki-validator-3.
Looking at the packages (with Wireshark), I noticed a significant number of DNS queries.
In order to get statistics, I installed the bind9 service on a server and what I could see in 30 minutes is surprising.

> cat queries.log | grep rpki.apnic.net | awk '{ print $5 }' |  awk -F\# '$1!="" { print $1 ;} ' | sort -n | uniq -c

`1987 172.16.50.2 (rpki-validator-2.24)` 
 `32     172.16.52.2 (rpki-validator-3-beta)`

> cat rpki-validator-app-2.24/conf/rpki-validator.conf

`validation.interval = 60m`

I think this is not normal

**Comment by MrCamp146** [comment]
> cat queries.log | grep query: | awk '{ print $8 }' | sort -nf | uniq -cdi | sort -nf
`4 rpki-pilot.lab.dtag.de`
`4 rpki-testbed.apnic.net`
`4 rrdp.ripe.net`
`6 www.ris.ripe.net`
`8 localcert.ripe.net`
`20 ca0.rpki.net`
`34 rpki-repository.nic.ad.jp`
`42 rpki.ripe.net`
`64 repository.lacnic.net`
`168 rrdp.apnic.net`
`190 ca.rg.net`
`190 rpki.cnnic.cn`
`422 rpki.afrinic.net`
`3673 rpki.apnic.net`

> cat queries.log | grep  rpki.apnic.net | awk '{ print $5 }' | awk -F# '$1!="" { print $1 ;} ' | sort -nf | uniq -cdi | sort -nf
 `44 172.16.52.2`
`3935 172.16.50.2`

> cat queries.log | grep  repository.lacnic.net | awk '{ print $5 }' | awk -F# '$1!="" { print $1 ;} ' | sort -nf | uniq -cdi | sort -nf
	`20 172.16.50.2`
	`46 172.16.52.2`
	
> cat queries.log | grep  rrdp.apnic.net | awk '{ print $5 }' | awk -F# '$1!="" { print $1 ;} ' | sort -nf | uniq -cdi | sort -nf
 `176 172.16.52.2`

> cat queries.log | grep ca.rg.net | awk '{ print $5 }' | awk -F# '$1!="" { print $1 ;} ' | sort -nf | uniq -cdi | sort -nf
     `14 172.16.50.2`
    `182 172.16.52.2`

>cat queries.log | grep  rpki.cnnic.cn | awk '{ print $5 }' | awk -F# '$1!="" { print $1 ;} ' | sort -nf | uniq -cdi | sort -nf
     `16 172.16.50.2`
    `180 172.16.52.2`

> cat queries.log | grep  rpki.afrinic.net | awk '{ print $5 }' | awk -F# '$1!="" { print $1 ;} ' | sort -nf | uniq -cdi | sort -nf
     `46 172.16.52.2`
    `376 172.16.50.2`

**Comment by timbru** [comment]
Hi,

The 2.24 version of the validator uses rsync by default, and the APNIC rsync repository is flat. This means that the validator needs to do a high number of rsync connections to get the APNIC RPKI repository.

APNIC do now support the new https based delta protocol (RRDP) and this is used by default (where available) by the 3.x version of the validator. This protocol is more efficient in that the full repository can be retrieved in one go, and from there on small deltas are retrieved. But in order to know about update the validator will retrieve a small notification file every minute.

We have done nothing special regarding DNS. But I expect that every fetch from the JVM would normally hit the local resolvers and they can take care of your normal caching, observing TTLs.

So, the number of queries might be high, but I don't see anything abnormal here.

**Comment by MrCamp146** [comment]
I think I found my problem.
On debina, the bind9 service is enabled, it has changed the TTL of all entries in its cache.
He changed it to 10 seconds.
It did not come from the application, but from a service activated by default.
I apologize for disturbing you.

**Comment by timbru** [comment]
No problem.
