### ISSUE TITLE
Allow a proxy to be set for rsync

### ISSUE THREAD

**Issue by DamianZaremba** [RIPE-NCC/rpki-validator#36]
Currently it is possible to use a proxy for HTTP requests via `jvm.proxy.http.host` & `jvm.proxy.http.port`, however this is not enough for all certificates to be successfully downloaded.

Passing the proxy over to the rsync calls would allow the application to function without direct internet access, which is (sadly) required in some implementations.

Taking an example failing call;
```
ERROR   [default-akka.actor.default-dispatcher-44] Rsync rsync command line: [rsync, --timeout=300, --update, --times, --copy-links, rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer, /opt/ripe-rpki-validator/data/rsync/rpki.ripe.net/ta]
ERROR   [default-akka.actor.default-dispatcher-44] Rsync rsync exit status: 10
ERROR   [default-akka.actor.default-dispatcher-44] Rsync rsync stderr: [rsync: failed to connect to rpki.ripe.net (193.0.6.138): Connection timed out (110), rsync: failed to connect to rpki.ripe.net (2001:67c:2e8:22::c100:68a): Network is unreachab
le (101), rsync error: error in socket IO (code 10) at clientserver.c(122) [Receiver=3.0.9]]
```

Setting the relevant environment variable, allows it to succeed;
```
RSYNC_PROXY=myproxy:3128 rsync --timeout=300 --update --times --copy-links rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer
The RIPE NCC Certification Repository is subject to Terms and Conditions
See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc

-rw-rw-r--        1038 2017/12/21 16:06:30 ripe-ncc-ta.cer
```

**Comment by timbru** [comment]
Hi Damian,

I will try to squeeze this into to the remaining work we're doing on the next version of the validator - where our current development efforts are focused: https://github.com/RIPE-NCC/rpki-validator-3

Can you confirm that having this in the 'rpki-validator.sh' script would solve your problem:
export RSYNC_PROXY=myproxy:3128

If so, then we would just need to update the start script. If not it will be more difficult, because we would have to pass the variable when do the system call to rsync.

**Comment by DamianZaremba** [comment]
Hi,

That does appear to resolve the issue.

Tested by setting the environment var via systemd, which the script is then exposed to rather than using export, though it should have the same effect.
